name: GitHub Actions Demo

on: [pull_request]

jobs:
  dummy-action-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to be uploaded to charmhub from the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: ğŸ–¨ Print the content of the charm
        run: |
          cat ${{ github.workspace }}/charm.py
      - run: echo "ğŸ This job's status is ${{ job.status }}."
